car_ads/urls.py
from django.urls import path
from car_ads import views
from django.views.static import serve

app_name= 'car_ads'

urlpatterns = [
    path('', views.ads.as_view(), name='ads'),
    path('update', views.update, name='update'),
    path('train', views.train, name='train'),
    path('predict', views.predict, name='predict'),
    path('get_models/', views.get_models, name='get_models'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('car_ads.urls')),
]

car_ads/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class ad(models.Model):
    ad_link = models.CharField(max_length=400, unique=True)
    brand = models.CharField(max_length=200,default='')
    model = models.CharField(max_length=200,default='')
    mileage = models.CharField(max_length=200,default='')
    year = models.CharField(max_length=200,default='')
    platform = models.CharField(max_length=200,default='')
    gearbox = models.CharField(max_length=200,default='')
    fuel = models.CharField(max_length=200,default='')
    price=models.CharField(max_length=200,default='')
    fh=models.CharField(max_length=200,default='')
    fiscal_power=models.CharField(max_length=200,default='')


    def __str__(self):
        return self.ad_link

car_ads/views.py
from django.shortcuts import render,redirect
from django.views.generic import (TemplateView, ListView, )
from car_ads.models import ad
import pandas as pd
import numpy as np
from urllib.parse import urlparse
from django.urls import reverse
import joblib
# Create your views here.
from django.db.models import F, Func, FloatField, ExpressionWrapper
from django.db.models.functions import Cast

class ads(TemplateView):

    template_name = 'ads.html'

    def get_context_data(self,*args, **kwargs):
        context = super(ads, self).get_context_data(*args,**kwargs)
        context['ads'] = ad.objects.all()
        context['qty'] = ad.objects.all().count()
        brands = ad.objects.order_by('brand').values_list('brand', flat=True).distinct()
        context['brands']=brands
        fuels = ad.objects.order_by('fuel').values_list('fuel', flat=True).distinct()
        context['fuels']=fuels
        x=self.request.GET.get('trained')
        if x=='1':
            context['trained']=1
        y=self.request.GET.get('prediction')
        if y is not None:
            context['prediction']=y
            reference_price_float=float(y)
            cars_queryset = ad.objects.exclude(price__exact='nan').annotate(
                price_diff=Cast(F('price'), FloatField()) - reference_price_float,
            )

            # Sort the queryset by the absolute difference in ascending order and retrieve the top 10 closest matches
            closest_matches = cars_queryset.order_by('price_diff')[:10]
            
            context['matches']=closest_matches
        
        return context

def brand_unique(x):
    if x=='ALFA' or x=='ALFA-ROMEO':
        return 'ALFA ROMEO'
    elif x=='MERCEDES' or x=='MERCEDES-BENZ':
        return 'MERCEDES BENZ'
    elif x=='LAND-ROVER':
        return 'LAND ROVER'
    else:
        return x

def First_hand(x):
    if x=='True' or x=='Oui' or x=='TRUE'or x==True:
        return 'Yes'
    else:
        return 'No'

def Gearbox(x):
    if x=='Automatique' or x==' Automatique':
        return 'Automatic'
    else:
        return 'Manual'

def Fuel(x):
    if x=='Diesel' or x=='Diesel ' or x==' Diesel':
        return 'diesel'
    elif x=='Essence':
        return 'gasoline'
    elif x=='Hybride':
        return 'hybrid'    
    elif x=='Electrique':
        return 'electric' 
    else:
        return 'gasoline'


def csv_to_df():

    df1=pd.read_csv('Kifal_data.csv')
    df2=pd.read_csv('Moteur_data.csv')
    df3=pd.read_csv('Avito_data.csv')
    df4=pd.read_csv('autocaz.csv')


    df1['brand']=df1['Make and Model'].apply(lambda x: x.split(' ')[0])
    df1['model']=df1['Make and Model'].apply(lambda x: x.split(' ')[1])
    df1=df1.drop(columns=['Make and Model', 'City', 'Origin','Type of Car','Title', 'Finish', 'Description','Features (Interior comfort, Driving assistance, Multimedia, Exterior aspects, Safety'])

    def df1_price(x):
        if pd.isna(x):
            return np.nan
        else:
            return x.split(' ')[0]+x.split(' ')[1]  

    df1['Price']=df1['Price'].fillna('- -').apply(lambda x: df1_price(x))
    df1['Mileage']=df1['Mileage'].str.replace("km", "")
    df1['Mileage']=df1['Mileage'].str.replace(" ", "")


    def df2_price(x):
        if pd.isna(x):
            return np.nan
        else:
            return x.split(' ')[0]+x.split(' ')[1]
    
    df2['brand']=df2['Brand']
    df2['model']=df2['Model and Version']
    df2=df2.drop(columns=['Brand','Date', 'City', 'Seller name','Model and Version','Body','Doors'])

    df2['Price']=df2['Price'].apply(lambda x: df2_price(x))
    df2['Mileage']=df2['Mileage'].str.replace(" ", "")

    
    df3['brand']=df3['Make']
    df3['model']=df3['Model']
    df3['Year']=df3['Year-Model']
    df3=df3.drop(columns=['Year-Model','Condition','Make','Origin','Advertiser','Title', 'City', 'Type','Model','Description','Equipment','Ad Date','Contact','Sector'])

    def df3_mileage(x):
        if pd.isna(x):
            return np.nan
        else:
            return x.split(' - ')[0].replace(" ", "")

    def df3_fiscal(x):
        if pd.isna(x):
            return np.nan
        else:
            return x.split(' ')[0]

    def df3_price(x):
        if pd.isna(x):
            return np.nan
        else:
            return str(int(x))

    df3['Mileage']=df3['Mileage'].apply(lambda x: df3_mileage(x))
    df3['Price']=df3['Price'].apply(lambda x: df3_price(x))
    df3['Fiscal Power']=df3['Fiscal Power'].apply(lambda x: df3_fiscal(x))



    def df4_price(x):
        if pd.isna(x):
            return np.nan
        else:
            return x.split(' ')[0]+x.split(' ')[1]
        
    df4['Price']=df4['price']
    df4['Year']=df4['year']
    df4['model']=df4['Model']
    df4=df4.drop(columns=['year','price','Model','Date of CME','Color','Category', 'Doors', 'Seats'])

    df4['Price']=df4['Price'].apply(lambda x: df4_price(x))

    df=pd.concat([df1,df2,df3,df4],ignore_index = True)
    
    
    size = len(df)
    for i in range (size):
        try:
            if len(df.loc[i]['brand'])==0:
                df.iloc[i, df.columns.get_loc('brand')]=df.loc[i]['model']
        except:
            df.iloc[i, df.columns.get_loc('brand')]=df.loc[i]['model']
    
    df = df[df['brand'].notna()]

    df['brand']=df['brand'].apply(lambda x: x.upper())
    df['brand']=df['brand'].apply(lambda x: brand_unique(x))

    df['First Hand']=df['First Hand'].apply(lambda x: First_hand(x))
    df['Gearbox']=df['Gearbox'].apply(lambda x: Gearbox(x))
    df['Fuel']=df['Fuel'].apply(lambda x: Fuel(x))

    return df

def update(request):

    ad.objects.all().delete()
    df=csv_to_df()
    size = len(df)

    for i in range (size):

        try:
            entry = ad (       
                                ad_link = df.loc[i]['Ad Link'],
                                brand = df.loc[i]['brand'],
                                model = df.loc[i]['model'],
                                mileage = df.loc[i]['Mileage'],
                                year = df.loc[i]['Year'],
                                platform = urlparse(df.loc[i]['Ad Link']).netloc,
                                gearbox = df.loc[i]['Gearbox'],
                                price=df.loc[i]['Price'],
                                fiscal_power=df.loc[i]['Fiscal Power'],
                                fh=df.loc[i]['First Hand'],
                                fuel=df.loc[i]['Fuel'],
                        )
            entry.save()
        except:
            pass
    

    return redirect ('/')

def train(request):
    df=csv_to_df()
    df=df.dropna()
    
    # Fuel = pd.get_dummies(df['Fuel'],drop_first=True)
    # df.drop(['Fuel'],axis=1,inplace=True)
    # df = pd.concat([df,Fuel],axis=1)


    from sklearn import preprocessing
    le1 = preprocessing.LabelEncoder()
    le2 = preprocessing.LabelEncoder()
    df['brand'] = le1.fit_transform(df['brand'])
    df['Fuel'] = le2.fit_transform(df['Fuel'])
    
    def First_hand(x):
        if x=='Yes':
            return 1
        else:
            return 0

    df['First Hand']=df['First Hand'].apply(lambda x: First_hand(x))

    def Gearbox(x):
        if x=='Automatic':
            return 1
        else:
            return 0
        
    df['Gearbox']=df['Gearbox'].apply(lambda x: Gearbox(x))
    df=df.drop(columns=['Ad Link', 'model'])
    df['Price']=df['Price'].astype(float)
    df['Gearbox']=df['Gearbox'].astype(float)
    df['Year']=df['Year'].astype(float)
    df['Fiscal Power']=df['Fiscal Power'].astype(float)
    df['Mileage']=df['Mileage'].astype(float)
    df['First Hand']=df['First Hand'].astype(float)
    df['brand']=df['brand'].astype(float)
    df['Fuel']=df['Fuel'].astype(float)


    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    from sklearn import metrics
    import numpy as np
    X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Price']), df['Price'], test_size=0.3, random_state=100)
    lm = LinearRegression()
    lm.fit(X_train,y_train)

    # predictions = lm.predict(X_test)
    # print(predictions)

    joblib.dump(lm, 'model.pkl')
    joblib.dump(le1, 'brand_encoder.pkl')
    joblib.dump(le2, 'fuel_encoder.pkl')

    redirect_url = reverse('car_ads:ads') + "?trained=1"

    return redirect (redirect_url)

def predict(request):

    if request.method == 'POST':
        model = joblib.load('model.pkl')
        brand_encoder = joblib.load('brand_encoder.pkl')
        fuel_encoder = joblib.load('fuel_encoder.pkl')

        fuel = request.POST.get('fuel')
        gearbox = request.POST.get('gearbox')
        year = request.POST.get('year')
        fiscal_power = request.POST.get('fiscal_power')
        mileage = request.POST.get('mileage')
        first_hand = request.POST.get('first_hand')
        brand = request.POST.get('brand')
        
        if first_hand=='Yes':
            first_hand=1
        else:
            first_hand=0

        if gearbox=='Automatic':
            gearbox=1
        else:
            gearbox=0

        brand = brand_encoder.transform([brand])[0]
        fuel = fuel_encoder.transform([fuel])[0]
        my_list = [fuel, gearbox, year, fiscal_power, mileage, first_hand, brand]
        float_list = [float(x) for x in my_list]
        X = [float_list]

        # Make predictions using the loaded model
        prediction = model.predict(X) - 15000

    prediction=str(int(np.round(prediction)[0]))
    redirect_url = reverse('car_ads:ads') + "?prediction=" + prediction

    return redirect (redirect_url)

templates/car_ads/ads.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<main class="container mt-4">

  <!-- Place for all ads table -->
  <section id="ads-table" class="my-5">
      <h2 class="text-center text-primary mb-3">All Ads Table</h2>
      <div class="card">
        <div class="card-body">
          <form method="POST" action="{% url 'car_ads:update' %}" class="post-form">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-danger update-button mx-auto d-block">Update</button>

            </form>
        </div>
    </div>
    <div class="card">
      <div class="card-body">
          <div class="table-responsive" style="height: 400px;"> <!-- You can adjust the height as needed -->
            {% if ads %}   
            <table class="table table-striped table-hover">
                  <thead>
                      <tr>
                          <th scope="col">#</th>
                          <th scope="col">Brand</th>
                          <th scope="col">Model</th>
                          <th scope="col">Mileage</th>
                          <th scope="col">Year</th>
                          <th scope="col">Gearbox</th>
                          <th scope="col">Fuel</th>
                          <th scope="col">Price</th>
                          <th scope="col">Fiscal Power</th>
                          <th scope="col">First Hand</th>
                          <th scope="col">Platform</th>
                          <th scope="col">Link</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for ad in ads %}
                      <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ ad.brand }}</td>
                          <td>{{ ad.model }}</td>
                          <td>{{ ad.mileage }}</td>
                          <td>{{ ad.year }}</td>
                          <td>{{ ad.gearbox }}</td>
                          <td>{{ ad.fuel }}</td>
                          <td>{{ ad.price }}</td>
                          <td>{{ ad.fiscal_power }}</td>
                          <td>{{ ad.fh }}</td>
                          <td>{{ ad.platform }}</td>
                          <td><a href="{{ ad.ad_link }}">{{ ad.ad_link }}</a></td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
              {% endif %}   
          </div>
      </div>
    </div>
  </section>

  <!-- Place for train predictor -->
  <section id="train-predictor" class="my-5">
      <h2 class="text-center text-primary mb-3">Train Estimator</h2>
      <div class="card">
          <div class="card-body">
            <div class="text-center">
            <form method="POST" action="{% url 'car_ads:train' %}" class="post-form">
              {% csrf_token %}
              {{form.as_p}}
              <button type="submit" class="btn btn-danger update-button mx-auto d-block">Train Estimator</button>
            </form>
            <p></p>
            {% if trained %}
              <p>Training Completed</p>
            {% endif %}
          </div>
          </div>
      </div>
  </section>

  <!-- Place for price predictor -->
  <section id="price-predictor" class="my-5">
      <h2 class="text-center text-primary mb-3">Price Estimator</h2>
      <div class="card">
          <div class="card-body">
            <div class="row mt-5">
              <div class="col">
                <p>Here you can enter the details of a car and get an estimated price.</p>
                <div id="prediction">
                  {% if prediction %}
                  <h2 id="predictionText">Predicted Price of Vehicle is {{ prediction }} DH</h2>
                  {% else %}
                  <h2 id="predictionText"></h2>
                  {% endif %}
              </div>
                <form id="predictForm" method="post" action="{% url 'car_ads:predict' %}" class="post-form">
                  {% csrf_token %}
                  <div class="row mb-3">
                    <div class="col">
                      <label for="fuel">Fuel:</label>
                      <select class="form-select" id="fuel" name="fuel">
                        {% for fuel in fuels %}
                        <option value="{{ fuel }}">{{ fuel }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col">
                      <label for="gearbox">Gearbox:</label>
                      <select class="form-select" id="gearbox" name="gearbox">
                        <option value="Manual">Manual</option>
                        <option value="Automatic">Automatic</option>
                      </select>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col">
                      <label for="year">Year:</label>
                      <input type="number" class="form-control" id="year" name="year" value="2010">
                    </div>
                    <div class="col">
                      <label for="fiscal_power">Fiscal Power:</label>
                      <input type="number" class="form-control" id="fiscal_power" name="fiscal_power" value="5.0">
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col">
                      <label for="mileage">Mileage:</label>
                      <input type="number" class="form-control" id="mileage" name="mileage" value="150000">
                    </div>
                    <div class="col">
                      <label for="first_hand">First Hand:</label>
                      <select class="form-select" id="first_hand" name="first_hand">
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                      </select>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col">
                      <label for="brand">Brand:</label>
                        <select class="form-select" id="brand" name="brand">
                          {% for brand in brands %}
                            <option value="{{ brand }}">{{ brand }}</option>
                          {% endfor %}
                        </select>
                    </div>
                    <div class="col">
                      <label for="model">Model:</label>
                        <select class="form-select" id="model" name="model">
                          {% for model in models %}
                            <option value="{{ model }}">{{ model }}</option>
                          {% endfor %}
                        </select>
                    </div>
                    
                  </div>
                  <button type="submit" class="btn btn-primary btn-lg">Estimate Price</button>
                </form>
              </div>
            
            </div>
          </div>
      </div>
  </section>

  <!-- Place for recommended ads table -->
  <section id="recommended-ads" class="my-5">
      <h2 class="text-center text-primary mb-3">Recommended Ads</h2>
      <div class="card">
          <div class="card-body">
            <p></p>
            <div class="table-responsive" style="height: 400px;"> <!-- You can adjust the height as needed -->
              <table class="table table-striped table-hover">
                <thead>
                  <th scope="col">Index</th>
                  <th scope="col">Brand</th>
                  <th scope="col">Model</th>
                  <th scope="col">Mileage</th>
                  <th scope="col">Year</th>
                  <th scope="col">Gearbox</th>
                  <th scope="col">Fuel</th>
                  <th scope="col">Price Difference</th>
                  <th scope="col">Fiscal Power</th>
                  <th scope="col">First Hand</th>
                  <th scope="col">Platform</th>
                  <th scope="col">Link</th>
         
                </thead>
                <tbody id="matchesTableBody">
                  {% for ad in matches %}  
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ ad.brand }}</td>
                    <td>{{ ad.model }}</td>
                    <td>{{ ad.mileage }}</td>
                    <td>{{ ad.year }}</td>
                    <td>{{ ad.gearbox }}</td>
                    <td>{{ ad.fuel }}</td>
                    <td>{{ ad.price }}</td>
                    <td>{{ ad.fiscal_power }}</td>
                    <td>{{ ad.fh }}</td>
                    <td>{{ ad.platform }}</td>
                    <td><a href="{{ ad.ad_link }}">{{ ad.ad_link }}</a></td>
  
                  </tr>
                  {% endfor %}
                </tbody>
                
                  
              </table>
          </div>
          </div>
      </div>
  </section>
</main>

<p></p>
<p></p>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        
        $("#brand").change(model);
        $('#predictForm').on('submit', function(event) {
          event.preventDefault();
  
          $.ajax({
              url: "{% url 'car_ads:predict' %}",
              type: 'POST',
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response) {
                  $('#predictionText').text("Predicted Price of Vehicle is " + response.prediction + " DH");
                  
                  console.log("S")
                  var matchesTableBody = $('#matchesTableBody');

                  matchesTableBody.empty();

                
                  var matches = response.matches;

                  for(var i = 0; i < matches.length; i++) {
                      var match = matches[i];
  
                      var row = "<tr>"
                          + "<td>" + (i + 1) + "</td>"
                          + "<td>" + match.brand + "</td>"
                          + "<td>" + match.model + "</td>"
                          + "<td>" + match.mileage + "</td>"
                          + "<td>" + match.year + "</td>"
                          + "<td>" + match.gearbox + "</td>"
                          + "<td>" + match.fuel + "</td>"
                          + "<td>" + match.price_diff + "</td>"
                          + "<td>" + match.fiscal_power + "</td>"
                          + "<td>" + match.fh + "</td>"
                          + "<td>" + match.platform + "</td>"
                          + "<td><a href="+ match.ad_link +">"+match.ad_link+"</a></td>"
                          + "</tr>";
                      matchesTableBody.append(row);
                  }
              
                },
              error: function(response) {
                  alert('Error! Please try again.');
              }
          });
      });
        
    });
    function model(){
      var selectedBrand = $(this).val();

      $.ajax({
          url: "{% url 'car_ads:get_models' %}",
          data: {
            'brand': selectedBrand
          },
          success: function(data) {
              var modelSelect = $('#model');
              modelSelect.html('');
              $.each(data.models, function(key, value) {
                  modelSelect.append('<option value="' + value + '">' + value + '</option>');
              });
          }
      });
    }
    </script>
{% endblock %}

templates/car_ads/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" rel="stylesheet">

        <style>
        table, th, td {
          border: 1px solid black;
          padding: 15px;
        }
        body {
          padding-bottom: 50px; /* set padding-bottom to 50 pixels */
        }
        </style>
    </head>        
    
    <body>
      
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">    
        <div class="container">   
          <a class="navbar-brand" href="#">Car Price Estimator</a>    
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">    
            <span class="navbar-toggler-icon"></span>    
          </button>    
          <div class="collapse navbar-collapse" id="navbarNav">    
            <ul class="navbar-nav ml-auto">    
              <li class="nav-item">    
                <a class="nav-link" href="#">Home</a>    
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


      <div class="content container">
        {% block content %}
        {% endblock %}
      </div>

    </body>

</html>